import type { Metadata } from "next";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core"
import "@fortawesome/fontawesome-svg-core/styles.css"
config.autoAddCss = false

import { Nunito, Poppins } from 'next/font/google'
import React from "react";

const nunito = Nunito({
  weight: "600",
  style: "normal",
  subsets: ["latin"],
  variable: "--font-nunito"
})

const poppins = Poppins({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Portfolio - Thomas Denoyelle",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="fr"
          className={`${nunito.variable} ${poppins.variable} h-full antialiased scroll-smooth`}
      >
      <body className={`font-nunito min-h-full flex flex-col`}>
      {children}
      </body>
      </html>
  );
}